Ticket5993 setup correctly
ISISComputingGroup/EPICS-Cryosms pull request #17
Opened 2021-03-22 17:36 UTC by ChrisColeExpControl

### Description of work

Implements more advanced ramp startup procedure, alongside a few fixes for errors  found in device testing.

### To test

https://github.com/ISISComputingGroup/IBEX/issues/5993

### Acceptance criteria
 - Changes made to macros to allow then to be loaded from GUI
 - When asked to start ramping, will first ramp to the persistent field if allowed
 - Will cool down after finishing ramping if in persistent mode
 - Will warm up before ramping (unless ramping to persistent)
 - Will display appropriate status messages when performing above operations
 - Will track stability of the heater temperature over pre-determined time
(Above outlined in slightly more detail in SMS software requirements document)

---

#### Code Review

- [ ] Does the IOC conform to IBEX standards?
    - [PV naming](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PV-Naming).
    - [Disable records](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Disable-records)
    - [Record simulation](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Record-Simulation)
    - [Finishing touches](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-Touches)
- [ ] Do the IOC and support module conform to the new [build guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reducing-Build-Dependencies)
- [ ] Have the changes been recorded appropriately in a PR for [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)?
- [ ] Is the device's flow control setting correct? [For most devices flow control should be OFF](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Flow-control).

### Functional Tests

- IOC responds correctly in:
    - [ ] Devsim mode
    - [ ] Recsim mode
    - [ ] Real device, if available
- [ ] Log files do not report undefined macros (serach for `macLib: macro` to find instances of `macLib: macro [macro name] is undefined...`

### Final steps

- [ ] Reviewer has merged the associated PR for the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)

2021-05-23 23:16 UTC, FreddieAkeroyd commented on cryosmsSup/cryosms.db
> +}
PP and MS have no meaning on FLNK, they only apply to OUT

2021-05-23 23:22 UTC, FreddieAkeroyd commented on cryosmsSup/cryosms.db
> +}
If you want to pass severity, you will need to use FLNK to trigger the next record which then reads the severity via its input link field (specifying MS)

2021-05-23 23:31 UTC, FreddieAkeroyd commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
>  			return asynSuccess;
Would it be possible to create the map in  CRYOSMSConfigure and pass to CRYOSMSDriver ? This avoid the duplication of arguments and possible ordering errors.

2021-05-23 23:37 UTC, FreddieAkeroyd commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
>  	}
Threre are a lot of arguments, are they always required or are their sensible defaults? If many could be considered optional then using syntax like   ("name1", "value1", "name2", "value2") and  `iocshArgArgv` is another option

2022-08-11 13:02 UTC, LowriJenkins requested changes

2022-08-11 13:02 UTC, LowriJenkins commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +		else if (heater_resp.find("OFF") != std::string::npos && heater_resp.find("AT") != std::string::npos) {
if we only expect "AT" if the response also contains off, do we actually need to check for both?
wouldn't 
```
if (heater_resp.find("ON") != std::string::npos) {
    //handles on case.
}
    else if (heater_resp.find("AT") != std::string::npos)
{
    //handles off + at case
}
else if (heater_resp.find("OFF") != std::string::npos) {
    //handles off but not at case
}else{
    //handles all other cases
}
```
Work just as well and simplify the check here somewhat?

2022-08-11 13:02 UTC, LowriJenkins commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +			int firstNum = heater_resp.find_first_of("1234567890");
can 0 be a valid first digit?

2022-08-11 13:02 UTC, LowriJenkins commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +			int lastNum = heater_resp.find_last_of("1234567890");
Not sure about this one, but if 0 is valid for both of these, you could possibly pull `"1234567890"` out into a constexpr char* to avoid the "magic number" though honestly, I think this is fairly clear as it is, and the compiler likely optimises string literals to constexpr anyway.

2022-08-11 13:02 UTC, LowriJenkins commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +			std::string persistStr(heater_resp, firstNum, lastNum);
This might be slightly more clear
```suggestion
			std::string persistStr = heater_resp.substr(firstNum, lastNum)
```

2022-08-11 13:02 UTC, LowriJenkins commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
>  	int trueVal = 1;
The trueVal and falseVal are defined to be 1 several times across this file, would it be easier to have them defined at the class level? rather than having multiple functions define them with the same value?

2022-08-11 13:02 UTC, LowriJenkins commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +	warming = (switchStat == 2 ? 1 : 0);
Your method might be preferred for visibility, but
```
if(switchStat==1){
    cooling = 1;
    warming = 0;
elseif(switchStat==2){
    cooling = 0;
    warming = 1;
else{
    cooling = 0;
    warming = 0
}
reduces the number of checks, on some execution paths, as it never needs to check if switchstat ==2 when we already know that it equals 1

2022-08-11 13:02 UTC, LowriJenkins commented on cryosmsSup/cryosms.db
> +record(ao, "$(P)CONSTANT:_SP")
Just wanted to check something that DB checker raised as a warning, you seem to have two records with the name `$(P)CONSTANT:_SP`, this one, and a readonly one at 498, is that ok in context of a readonly record?

2022-08-11 13:02 UTC, LowriJenkins commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +	epicsThreadSleep(5);
This a fairly long sleep here, does it always have to be this long? If not is there something that we can check to see if it should stop early and then do a loop of shorter waits?

2022-08-12 12:11 UTC, LilithCole commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +			int firstNum = heater_resp.find_first_of("1234567890");
yes, e.g. 0.5

2022-08-12 13:33 UTC, LowriJenkins approved these changes

2022-08-12 13:57 UTC, merged