Ticket 4831 cryosms simple start
ISISComputingGroup/EPICS-Cryosms pull request #2
Opened 2019-11-01 17:02 UTC by ChrisColeExpControl

### Description of work

IOC now performs startup logic

### To test

https://github.com/ISISComputingGroup/IBEX/issues/4831

### Acceptance criteria

new tests pass

---

#### Code Review

### Functional Tests

- IOC responds correctly in:
    - [ ] Devsim mode
    - [ ] Recsim mode
    - [ ] Real device, if available
- [ ] Supplementary IOCs (`..._0n` where `n>1`) run correctly
- [ ] Log files do not report undefined macros (serach for `macLib: macro` to find instances of `macLib: macro [macro name] is undefined...`

2019-11-20 17:17 UTC, Alistair-McGann-Tessella requested changes
This is a very complicated IOC. The structure of the db file is good and it seems to cover most of the funcitonality required well. Most of the changes suggested are minor bug fixes and documentation, which is pretty good given the complexity of the device. 👍 

I think it would be useful to add to the wiki page which parameters we expect the users to change, and a brief comment saying that IOC initialisation is done in the asyn driver and why. This will make it clearer to someone supporting this device.

It is worth thinking if any of the PVs should be labelled as interesting and archived.

When I ran the IOC system tests there was quite a lot of errors because of mismatches in the protocols which normally we wouldn't expect to see. There might need to be some work on the emulator and the protocol files to fix these bugs.

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +		status = putDb("MAGNET:MODE", &magMode);
I'm not sure what the behaviour will be here, it appears that a string is getting written to a binary (bo) record?

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +	if (std::getenv("USE_SWITCH") == "Yes" && (std::getenv("SWITCH_TEMP_PV") == NULL || std::getenv("SWITCH_HIGH") == NULL || std::getenv("SWITCH_LOW") == NULL ||
The switching variables are different here to the specification documentation. `SWITCH_TIMEOUT` is missing from this list, and `SWITCH_TOLERANCE`, `SWITCH_TEMP_TOLERANCE`, `HEATER_OUT` have been added?

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on cryosmsSup/cryosms.proto
> +	out "S H %f";
This is different to the design document, which specifies `SH`.

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on cryosmsSup/cryosms.db
> +    field(FLNK, "$(P)GAUSS")
This is pointing to a PV which does not exist. Is this PV missing or should it be pointing somewhere else?

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +asynStatus CRYOSMSDriver::onStart()
I think it's important that the logic here is tested so we are aware if we introduce a bug at a later date. I recommend splitting the if statements up into logical chunks and using googletest to unit test each chunk.

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on cryosmsSup/cryosms.proto
> +	in "%*8c HEATER STATUS: %s";
%s is not a valid return type for a bi record (causes error in devsim log)

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on cryosmsSup/cryosms.proto
> +	out "HEATER";
This command doesn't seem to be in the emulator and causes an error to be reported in the devsim log.

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on cryosmsSup/cryosms.proto
> +	in "%*8c OUTPUT: %f %(\$1OUTPUT:RAW:UNIT){AMPS|TESLA} AT %(\$1OUTPUT:VOLT)f VOLTS";
This input doesn't seem to match the device's emulator. Possibly mismatches a trailing space at the end of the response?

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on cryosmsSup/cryosms.proto
> +	in "%*8c MAX SETTING: %*f %*{AMPS|TESLA}";
Response from the emulator does not seem to match this. Perhaps an issue with line terminators?

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on cryosmsSup/cryosms.db
> +### HIDDEN:
If these are 'internal' PVs that aren't user-facing, our convention is to mark private records by putting an underscore in the name, see (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PV-Naming#private-names).

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on cryosmsSup/cryosms.db
> +    field(SIML, "$(P)SIM")
This record looks like it's mismatching with the emulator and adding an error to the log file

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on cryosmsSup/cryosms.db
> +    field(INP, "@cryosms.proto getOutput($(P)) $(PORT)")
This protocol also has a mismatch with the emulator, it looks like a CRLF at the end of the return statement. See the devsim logs.

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on cryosmsSup/cryosms.db
> +    field(INP, "@cryosms.proto getRampStatus $(PORT)")
Mismatches when running against emulator

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +	static const iocshArg initArg0 = { "portName", iocshArgString };			///< Port to connect to
👍 Much clearer

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +asynStatus CRYOSMSDriver::onStart()
When started through the IOC test framework these were the commands issued over asyn (logged using an asyn trace mask). This is a different order to what I was expecting from the specification for the cryo sms:

```
SET TPA 0.037000
T OFF
SET MAX 135.000000
SET RAMP 1.120000
P
HEATER
GET SIGN
T ON
T
RAMP STATUS
GET O
GET RATE
T
```

If this is the expected command set on booting with the parameters in the IOC test framework this should be noted in the documentation

2019-11-20 17:17 UTC, Alistair-McGann-Tessella commented on cryosmsSup/cryosms.db
> -record(bi, "$(P)SIM")
The SIM and DISABLE records are common to all IOCs to make sure that records behave correctly in recsim. Is there a reason that they have been removed?

2020-01-03 11:11 UTC, Alistair-McGann-Tessella reviewed
Much tidier now, the bulk of my comments fall in to either documentation (e.g. docstrings for the new functions) and error handling (e.g. adding errors to the IOC log file). The google tests are a really useful tool to keep this maintainable in the future.

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +asynStatus CRYOSMSDriver::checkTToA()
Can you add some documentation, like a python docstring, which explains what each of these functions do and their in/outputs?

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +	asynStatus status;
`status` is the return value for this function, but I can't see where it's modified here. Perhaps this should be initialised to asynSuccess or similar? This applies to other functions

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +	int trueVal = 1;
Can you use c++ booleans instead of defining your own?

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on cryosmsSup/cryosms.db
> +record(bo, "$(P)RAMP:LEADS")
Does this record need ONAM and ZNAM set to true/false?

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +			this->writeDisabled = TRUE;
Should this condition also have something written to the STAT pv?

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +#define INIT_ROW_NUM 60
Can you add what this represents in a comment?

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +asynStatus CRYOSMSDriver::checkRampFile()
This function is used only to set the ramp rates in the IOC test framework tests (if I understand the test correctly). Is this still the best place to put this code? If so, can it be documented on the wiki. It also needs comments explaining what it does

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +	epicsThreadSleep(0.2);//ramp not set correctly unless we wait briefly here
Do we understand why this is required?

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/tests/CRYOSMSTests.cc
> +#include <Windows.h>
Do these tests depend on a windows system? This will not work in the red hat build

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +		double teslaToAmps = std::stod(envVarMap.at("T_TO_A"));
There should be some error handling here in case std::stod can't convert the environment variable to a double.

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +asynStatus CRYOSMSDriver::checkMaxVolt()
I couldn't see any tests for this function

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +asynStatus CRYOSMSDriver::checkWriteUnit()
I couldn't find any tests for this function

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/tests/CRYOSMSTests.cc
> +		ASSERT_EQ(testDriver->writeDisabled, 0);
`writeDisabled` defaults to FALSE (0) in the CRYOSMSDriver class. This means that this test (and other tests which check writeDisabled is false or 0) could produce a false positive, as it would pass even if the code this tests doesn't do any operations.

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +{
Could do with a docstring explaining the setup this is doing and a very brief explanation of how. This would make it easier to follow

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +	int trueVal = 1;
There are a few places where values are assigned 1 or 0 like a boolean. Can booleans (`true`/`false`) from C++ or `stdbool.h` from C be used instead?

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on cryosmsSup/cryosms.db
> +record(calc, "$(P)READY")
I would expect this to be supplied to the user as a binary output with Yes/No as string values.

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on cryosmsSup/cryosms.db
> +    field(OUT, "@cryosms.proto setOutputMode $(PORT)")
This record still seems to have problems with its line termination, I am getting the following error in my devsim log running the python tests:
```
2020/01/02 18:24:56.354304 L0 TE:NDW1836:CRYOSMS_01:HEATER:STAT: 2 bytes surplus input "<0d><0a>"
2020/01/02 18:24:56.354315 L0 TE:NDW1836:CRYOSMS_01:HEATER:STAT: after 27 bytes ".... HEATER STATUS: OFF"
```

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on cryosmsSup/cryosms.proto
> +setHeaterValue {
Does this need to have `InTerminator = CR LF 0x13`? I think this is causing the python test to fail

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +#define RETURN_IF_ASYNERROR(func, ...) status = (func)(__VA_ARGS__); \
If there is a problem when calling the supplied function it would be good to rethrow the error in the log file using `errlogSevPrintf`. This would make debugging a lot easier, as we would know where the problem occured and with which arguments.

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +		const char *statMsg = "No calibration from Tesla to Amps supplied";
All of these error messages should also appear in the IOC log. This is to help debugging, and can be done with `errlogSevPrintf`.

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/tests/CRYOSMSTests.cc
> +	TEST_F(StartupTests, test_GIVEN_use_switch_yes_WHEN_a_required_value_null_THEN_write_disabled)
Ideally, tests like this would be parameterised such that we know that all combinations of NULL/not NULL work for all the environment variables. However, testing one is absolutely good enough, especially given the size of the ticket. I don't suggest these changes unless it's a trivial (<20 minute) job

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/tests/run_all_tests.cc
> +}
Needs a new line at the end of the file

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +	pMaxT_ = (epicsFloat64 *)calloc(INIT_ROW_NUM, sizeof(epicsFloat64));
It's not immediately obvious what these variables do and why they are constructed like this, a comment explaining this would be useful. Becuase they call `calloc`, it's also important to call `free` after they are no longer useful to stop a memory leak.

2020-01-03 11:11 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +		envVarMap.insert(std::pair<std::string, const char* >(envVar, std::getenv(envVar.c_str())));
👍 This is a really good way of ensuring that all the environment variables are available here and can be modified by the tests

2020-01-22 13:52 UTC, ChrisColeExpControl commented on cryosmsSup/cryosms.proto
> +	out "S H %f";
the design document is incorrect in this instance, command is indeed `S H`

2020-01-22 14:00 UTC, ChrisColeExpControl commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +	int trueVal = 1;
In order to set the pvs to their desired states we need to pass a reference to the required integers. I chose to name them trueVal and falseVal purely for readability.

2020-02-13 16:29 UTC, Alistair-McGann-Tessella requested changes

2020-02-13 16:29 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +	asynStatus status;
Initialise to asynSuccess?

2020-02-13 16:29 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +	asynStatus status;
Initialise to asynSuccess

2020-02-13 16:29 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +	asynStatus status;
Initialise

2020-02-13 16:29 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/CRYOSMSDriver.cpp
> +	asynStatus status;
Initialise

2020-02-13 16:29 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/tests/CRYOSMSTests.cc
> +	TEST_F(StartupTests, test_GIVEN_allow_persist_yes_WHEN_required_values_exist_THEN_write_enabled)
Can there be a test for the case when allow_persist isn't set to `yes`? Could also be applied to other functions

2020-02-13 16:29 UTC, Alistair-McGann-Tessella commented on CRYOSMSApp/src/tests/CRYOSMSTests.cc
> +		testDriver->envVarMap["USE_MAGNET_TEMP"] = "Yes";
This sets `use_magnet_temp` to yes?

2020-02-14 17:10 UTC, Alistair-McGann-Tessella approved these changes

2020-02-14 17:16 UTC, merged